language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get -v github.com/robertkrimen/otto/otto # Download otto JS interpreter
  - sudo apt-get install lcov
  - yarn install
script:
  - yarn lint
  - FORCE_COLOR=true yarn test
  - yarn test:c --silent
  - otto src/decoder.js # Run through otto (used by TTN)
  - otto src/encoder.js # Run through otto (used by TTN)
after_success:
  - yarn coverage
  - yarn coveralls
  - yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
